repos:
  - repo: local
    hooks:
      - id: prettier-check
        name: Check prettier formatting
        entry: bun run format:check
        language: system
        files: \.(js|ts|vue|scss|css|json|yml|yaml)$
        exclude: ^\.nuxt/|^\.output|^dist|^node_modules/|^bun\.lock|^\.tem|^wt.*|^infra/backup$
        pass_filenames: false
