name: Set up infrastructure
run-name: Set up infrastructure (${{ github.ref_name }})

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [staging]
  workflow_dispatch:

env:
  # Expects credentials for service account:
  #   {environment}-deployer@veracioux.iam.gserviceaccount.com
  GCP_SA_KEY: |-
    ${{ secrets.GCP_SA_KEY }}

jobs:
  terraform-apply-or-plan:
    name: Terraform Apply (Staging) or Plan and create PR (Prod)
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'staging' && 'stg' || 'dev' }}
    env:
      environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'staging' && 'stg' || 'dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: |-
            ${{ env.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Select ${{ env.environment }} workspace
        working-directory: infra
        run: |
          mkdir -p .terraform
          echo ${{ env.environment }} > .terraform/environment

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        if: github.ref_name == 'staging'
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Terraform Plan
        if: github.ref_name == 'staging'
        working-directory: infra
        run: |
          terraform plan -out prod.tfplan > plan_output.log 2>&1
          echo "PLAN_OUTPUT<<EOF" >> $GITHUB_ENV
          cat plan_output.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload plan to GCS
        if: github.ref_name == 'staging'
        run: gcloud storage cp infra/prod.tfplan gs://veracioux-tfstate/${{ github.sha }}-prod.tfplan

      - name: Create PR with plan output
        if: github.ref_name == 'staging'
        run: |
          gh pr create --base main --head staging --title "Terraform Plan for Prod" --body "${{ env.PLAN_OUTPUT }}"

      # - name: Download plan from GCS
      #   if: github.ref_name == 'main'
      #   run:
      #     SHA="$(git rev-parse HEAD^2)"
      #     gcloud storage cp gs://veracioux-tfstate/plans/"$SHA".tfplan infra/prod.tfplan

      # - name: Terraform Apply Plan
      #   if: github.ref_name == 'main'
      #   working-directory: infra
      #   run: terraform apply -auto-approve prod.tfplan
